# Generated by Django 4.2.7 on 2023-11-16 21:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Transferencias Internas', 'Transferencias Internas'), ('Transferencias Otros Bancos', 'Transferencias Otros Bancos')], max_length=255)),
                ('date_time_transaction', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_account', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_account', models.CharField(max_length=255)),
                ('date_time_registered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('destination_financial_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_destination', to='accounting.financialentity')),
                ('origin_financial_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_origin', to='accounting.financialentity')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
